import type { CSSProperties } from "react";
import type { Habit } from "../../lib/domain/tracker-state";

export function MotivationManagerDialog({ motivations, draft, editingIndex, onDraftChange, onEdit, onDelete, onCancelEdit, onSave, onClose }: { motivations: string[]; draft: string; editingIndex: number | null; onDraftChange: (value: string) => void; onEdit: (index: number) => void; onDelete: (index: number) => void; onCancelEdit: () => void; onSave: () => void; onClose: () => void }) {
  return <div className="modal-backdrop" role="presentation" onMouseDown={onClose}><div className="modal motivations-modal" role="dialog" aria-modal="true" aria-labelledby="motivations-title" onMouseDown={(event) => event.stopPropagation()}>
    <button className="close" onClick={onClose} aria-label="Cerrar">×</button><p className="eyebrow">TU VOZ INTERIOR</p><h2 id="motivations-title">Frases motivacionales</h2><p className="modal-help">Cada día aparecerá una frase distinta en el acceso. Las que añadas aquí tendrán prioridad sobre las predeterminadas.</p>
    <div className="motivation-editor"><label>Frase<textarea autoFocus value={draft} maxLength={220} onChange={(event) => onDraftChange(event.target.value)} placeholder="Ej. La dirección importa más que la velocidad." /></label><div className="motivation-editor-actions">{editingIndex !== null && <button className="reset-button" onClick={onCancelEdit}>Cancelar</button>}<button className="add-button" onClick={onSave}>{editingIndex === null ? "+ Añadir frase" : "Guardar cambios"}</button></div></div>
    <div className="motivation-list" aria-live="polite">{motivations.map((motivation, index) => <div className="motivation-row" key={`${motivation}-${index}`}><span>{index + 1}</span><p>“{motivation}”</p><button className="menu-trigger" onClick={() => onEdit(index)} aria-label={`Editar frase ${index + 1}`}>✎</button><button className="menu-trigger danger-text" onClick={() => onDelete(index)} aria-label={`Eliminar frase ${index + 1}`}>×</button></div>)}{!motivations.length && <p className="empty-motivations">No hay frases personales. Mientras tanto se mostrarán las frases predeterminadas.</p>}</div>
  </div></div>;
}

export function HabitActionDialog({ type, habit, onEdit, onArchive, onDelete, onClose }: { type: "daily" | "weekly"; habit: Habit; onEdit: (type: "daily" | "weekly", habit: Habit) => void; onArchive: (type: "daily" | "weekly", id: number) => void; onDelete: (target: { type: "daily" | "weekly"; id: number; name: string }) => void; onClose: () => void }) {
  return <div className="modal-backdrop action-backdrop" role="presentation" onMouseDown={onClose}><div className="action-sheet" role="dialog" aria-modal="true" aria-labelledby="actions-title" onMouseDown={(event) => event.stopPropagation()}>
    <div className="action-sheet-head"><div><p className="eyebrow">GESTIONAR HÁBITO</p><h2 id="actions-title">{habit.name}</h2></div><button className="close static-close" onClick={onClose} aria-label="Cerrar">×</button></div>
    <button onClick={() => onEdit(type, habit)}><strong>Editar</strong><span>Cambiar el bloque, nombre, objetivo o color</span></button><button onClick={() => onArchive(type, habit.id)}><strong>Archivar</strong><span>Ocultarlo conservando su historial</span></button><button className="danger-action" onClick={() => onDelete({ type, id: habit.id, name: habit.name })}><strong>Eliminar</strong><span>Borrar el hábito y todos sus registros</span></button>
  </div></div>;
}

export function DeleteHabitDialog({ name, onClose, onDelete }: { name: string; onClose: () => void; onDelete: () => void }) {
  return <div className="modal-backdrop" role="presentation" onMouseDown={onClose}><div className="modal confirm-modal" role="alertdialog" aria-modal="true" aria-labelledby="delete-title" onMouseDown={(event) => event.stopPropagation()}><p className="eyebrow danger-text">ACCIÓN IRREVERSIBLE</p><h2 id="delete-title">¿Eliminar “{name}”?</h2><p>Se borrarán también todos sus registros y se desvinculará de los objetivos que lo utilicen. Si quieres conservar el historial y los vínculos, utiliza “Archivar”.</p><div className="confirm-actions"><button className="reset-button" onClick={onClose}>Cancelar</button><button className="delete-button" onClick={onDelete}>Eliminar definitivamente</button></div></div></div>;
}

export function StreakCelebrationDialog({ name, color, onClose }: { name: string; color: string; onClose: () => void }) {
  return <div className="modal-backdrop celebration-backdrop" role="presentation" onMouseDown={onClose}><div className="celebration-modal" role="dialog" aria-modal="true" aria-labelledby="celebration-title" onMouseDown={(event) => event.stopPropagation()} style={{ "--habit-color": color } as CSSProperties}><button className="close celebration-close" onClick={onClose} aria-label="Cerrar">×</button><div className="compass-celebration" aria-hidden="true"><span className="compass-north">N</span><span className="compass-needle" /><span className="compass-center" /></div><p className="eyebrow">RUMBO CONSOLIDADO</p><h2 id="celebration-title">¡30 días consecutivos!</h2><p>Has mantenido <strong>{name}</strong> durante 30 días seguidos. Ya no es solo un objetivo: estás construyendo una identidad.</p><button className="add-button full" onClick={onClose}>Seguir avanzando</button></div></div>;
}
