import type { RefObject } from "react";
import type { BackupPreview } from "../../lib/domain/backup";
import type { Category, Goal, Habit, HabitCategory, WeeklyHabit } from "../../lib/domain/tracker-state";

export function CategoryManagerDialog({ categories, daily, weekly, goals, editingCategoryId, name, icon, color, icons, palette, onNameChange, onIconChange, onColorChange, onTogglePriority, onEdit, onRequestDelete, onCancelEdit, onSave, onClose }: {
  categories: Category[]; daily: Habit[]; weekly: WeeklyHabit[]; goals: Goal[]; editingCategoryId: HabitCategory | null;
  name: string; icon: string; color: string; icons: string[]; palette: string[];
  onNameChange: (value: string) => void; onIconChange: (value: string) => void; onColorChange: (value: string) => void;
  onTogglePriority: (id: HabitCategory) => void; onEdit: (category: Category) => void; onRequestDelete: (id: HabitCategory) => void;
  onCancelEdit: () => void; onSave: () => void; onClose: () => void;
}) {
  return <div className="modal-backdrop" role="presentation" onMouseDown={onClose}><div className="modal blocks-modal" role="dialog" aria-modal="true" aria-labelledby="blocks-title" onMouseDown={(event) => event.stopPropagation()}>
    <button className="close" onClick={onClose} aria-label="Cerrar">×</button><p className="eyebrow">ORGANIZACIÓN PERSONAL</p><h2 id="blocks-title">Gestionar bloques</h2>
    <div className="block-manager-list">{categories.map((category) => {
      const habitCount = [...daily, ...weekly].filter((habit) => !habit.archived && habit.category === category.id).length;
      const goalCount = goals.filter((goal) => goal.status !== "discarded" && goal.category === category.id).length;
      return <div className="block-manager-row" key={category.id}><span className="block-manager-icon" style={{ background: `${category.color}26`, color: category.color }}>{category.icon}</span><div><strong>{category.label}</strong><small>{habitCount} {habitCount === 1 ? "hábito" : "hábitos"} · {goalCount} {goalCount === 1 ? "objetivo" : "objetivos"}</small></div><button className={`priority-toggle ${category.priority ? "active" : ""}`} onClick={() => onTogglePriority(category.id)} aria-label={`${category.priority ? "Quitar prioridad a" : "Marcar como prioritario"} ${category.label}`} aria-pressed={Boolean(category.priority)} title={category.priority ? "Bloque prioritario (peso 2)" : "Bloque normal (peso 1)"}>★</button><button className="menu-trigger" onClick={() => onEdit(category)} aria-label={`Editar bloque ${category.label}`}>✎</button><button className="menu-trigger danger-text" disabled={categories.length === 1} onClick={() => onRequestDelete(category.id)} aria-label={`Eliminar bloque ${category.label}`}>×</button></div>;
    })}</div>
    <div className="block-editor"><p className="eyebrow">{editingCategoryId ? "EDITAR BLOQUE" : "NUEVO BLOQUE"}</p><div className="block-fields"><label>Nombre<input value={name} onChange={(event) => onNameChange(event.target.value)} placeholder="Ej. Ocio" /></label><label className="icon-field">Personalizado<input value={icon} maxLength={2} onChange={(event) => onIconChange(event.target.value)} aria-label="Icono personalizado del bloque" /></label></div>
      <fieldset className="block-icon-picker"><legend>Icono</legend><div className="block-icon-grid">{icons.map((item) => <button key={item} type="button" className={icon === item ? "selected" : ""} style={{ color: icon === item ? color : undefined }} onClick={() => onIconChange(item)} aria-label={`Elegir icono ${item}`} aria-pressed={icon === item}>{item}</button>)}</div><small>Elige uno de la paleta o escribe tu propio símbolo arriba.</small></fieldset>
      <fieldset className="color-picker compact-colors"><legend>Color</legend><div className="color-palette">{palette.map((item) => <button key={item} type="button" className={color === item ? "selected" : ""} style={{ background: item }} onClick={() => onColorChange(item)} aria-label={`Elegir color ${item}`} aria-pressed={color === item}>{color === item && <span>✓</span>}</button>)}</div></fieldset>
      <div className="block-editor-actions">{editingCategoryId && <button className="reset-button" onClick={onCancelEdit}>Cancelar edición</button>}<button className="add-button" onClick={onSave}>{editingCategoryId ? "Guardar bloque" : "+ Añadir bloque"}</button></div>
    </div>
  </div></div>;
}

export function BackupManagerDialog({ inputRef, message, preview, onInspect, onExport, onRestore, onClose }: { inputRef: RefObject<HTMLInputElement | null>; message: string; preview: BackupPreview | null; onInspect: (file?: File) => void; onExport: () => void; onRestore: () => void; onClose: () => void }) {
  return <div className="modal-backdrop" role="presentation" onMouseDown={onClose}><div className="modal backup-modal" role="dialog" aria-modal="true" aria-labelledby="backup-title" onMouseDown={(event) => event.stopPropagation()}>
    <button className="close" onClick={onClose} aria-label="Cerrar">×</button><p className="eyebrow">PORTABILIDAD Y RECUPERACIÓN</p><h2 id="backup-title">Copia de tus datos</h2><p>Descarga una copia completa de hábitos, objetivos, bloques, historial y frases. Guárdala en un lugar seguro.</p>
    <button className="add-button full" type="button" onClick={onExport}>Descargar copia JSON</button><div className="backup-divider"><span>Restaurar una copia</span></div>
    <input ref={inputRef} className="backup-file-input" type="file" accept="application/json,.json" onChange={(event) => onInspect(event.target.files?.[0])} /><button className="reset-button full" type="button" onClick={() => inputRef.current?.click()}>Seleccionar archivo</button>
    {message && <p className="import-message" role="alert">{message}</p>}{preview && <div className="backup-preview"><strong>Copia válida</strong><span>{preview.daily} hábitos diarios · {preview.weekly} semanales</span><span>{preview.goals} objetivos · {preview.categories} bloques · {preview.motivations} frases</span><p>Restaurar sustituirá todos los datos actuales. No se fusionarán ambas versiones.</p><button className="danger-button full" type="button" onClick={onRestore}>Confirmar y sustituir mis datos</button></div>}
  </div></div>;
}

export function ArchivedManagerDialog({ goals, habits, categories, resolveHabitCategory, onRestoreGoal, onRestoreHabit, onClose }: { goals: Goal[]; habits: { type: "daily" | "weekly"; habit: Habit }[]; categories: Category[]; resolveHabitCategory: (habit: Habit) => HabitCategory; onRestoreGoal: (id: number) => void; onRestoreHabit: (type: "daily" | "weekly", id: number) => void; onClose: () => void }) {
  const archivedCount = goals.length + habits.length;
  return <div className="modal-backdrop" role="presentation" onMouseDown={onClose}><div className="modal archived-modal" role="dialog" aria-modal="true" aria-labelledby="archived-title" onMouseDown={(event) => event.stopPropagation()}>
    <button className="close" onClick={onClose} aria-label="Cerrar">×</button><p className="eyebrow">HISTORIAL CONSERVADO</p><h2 id="archived-title">Elementos archivados</h2>
    {archivedCount === 0 ? <div className="archived-empty"><strong>No tienes elementos archivados</strong><p>Cuando archives un hábito u objetivo, podrás encontrarlo y restaurarlo desde aquí sin perder su historial.</p></div> : <div className="archived-sections">
      <section className="archived-section"><h3>Objetivos <span>{goals.length}</span></h3>{goals.length ? <div className="archived-list">{goals.map((goal) => { const category = categories.find((item) => item.id === goal.category); const periodLabel = { daily: "Diario", weekly: "Semanal", monthly: "Mensual", yearly: "Anual" }[goal.period]; return <div className="archived-row" key={`goal-${goal.id}`}><i style={{ background: category?.color ?? "#39c6a4" }} /><div><strong>{goal.title}</strong><small>{periodLabel}{category ? ` · ${category.label}` : ""} · {goal.status === "completed" ? "Completado" : "En curso"}</small></div><button className="restore-button" onClick={() => onRestoreGoal(goal.id)}>Restaurar</button></div>; })}</div> : <p className="archived-section-empty">No hay objetivos archivados.</p>}</section>
      <section className="archived-section"><h3>Hábitos <span>{habits.length}</span></h3>{habits.length ? <div className="archived-list">{habits.map(({ type, habit }) => { const category = categories.find((item) => item.id === resolveHabitCategory(habit)); return <div className="archived-row" key={`${type}-${habit.id}`}><i style={{ background: habit.color }} /><div><strong>{habit.name}</strong><small>{type === "daily" ? "Diario" : "Semanal"}{category ? ` · ${category.label}` : ""}</small></div><button className="restore-button" onClick={() => onRestoreHabit(type, habit.id)}>Restaurar</button></div>; })}</div> : <p className="archived-section-empty">No hay hábitos archivados.</p>}</section>
    </div>}
  </div></div>;
}

export function DeleteCategoryDialog({ categoryId, replacementId, categories, onReplacementChange, onClose, onDelete }: { categoryId: HabitCategory; replacementId: HabitCategory; categories: Category[]; onReplacementChange: (id: HabitCategory) => void; onClose: () => void; onDelete: () => void }) {
  return <div className="modal-backdrop" role="presentation" onMouseDown={onClose}><div className="modal confirm-modal" role="alertdialog" aria-modal="true" aria-labelledby="delete-block-title" onMouseDown={(event) => event.stopPropagation()}><p className="eyebrow danger-text">ELIMINAR BLOQUE</p><h2 id="delete-block-title">¿Dónde movemos sus elementos?</h2><p>El bloque desaparecerá, pero sus hábitos, objetivos y todo su historial se conservarán.</p><label>Bloque de destino<select value={replacementId} onChange={(event) => onReplacementChange(event.target.value)}>{categories.filter((category) => category.id !== categoryId).map((category) => <option key={category.id} value={category.id}>{category.label}</option>)}</select></label><div className="confirm-actions"><button className="reset-button" onClick={onClose}>Cancelar</button><button className="delete-button" onClick={onDelete}>Mover y eliminar</button></div></div></div>;
}
