import { habitScheduledOnDate, isoDate, type HabitSchedule } from "./tracking";

export type InsightHabit = { id: number; name: string; goal: number; category?: string; archived?: boolean; archivedAt?: string; weekdaysOnly?: boolean; schedule?: HabitSchedule; history?: Record<string, number[]>; skips?: Record<string, number[]> };
export type InsightGoal = { id: number; title: string; dueDate: string; period?: "daily" | "weekly" | "monthly" | "yearly"; status: "active" | "completed" | "discarded"; archived?: boolean; currentValue: number; targetValue: number; steps?: { title: string; dueDate: string; completed: boolean }[] };
export type ActionableInsight = { id: string; kind: "trend" | "weekday" | "habit" | "goal"; entityId?: number; title: string; detail: string; evidence: string; rule: string; period: string; action: string; severity: "attention" | "positive" | "neutral" };
type Sample = { scheduled: number; completed: number };

function addDays(date: Date, amount: number) { const result = new Date(date.getFullYear(), date.getMonth(), date.getDate(), 12); result.setDate(result.getDate() + amount); return result; }
function recordFor(habit: InsightHabit, date: Date) { const key = isoDate(date.getFullYear(), date.getMonth(), date.getDate()); if (!habitScheduledOnDate(habit, key)) return null; const monthKey = key.slice(0, 7); const day = date.getDate(); if ((habit.skips?.[monthKey] ?? []).includes(day)) return null; return (habit.history?.[monthKey] ?? []).includes(day); }
function sample(habits: InsightHabit[], start: Date, days: number, category?: string): Sample { const result = { scheduled: 0, completed: 0 }; for (let offset = 0; offset < days; offset += 1) { const date = addDays(start, offset); habits.filter((habit) => !category || habit.category === category).forEach((habit) => { const completed = recordFor(habit, date); if (completed === null) return; result.scheduled += 1; if (completed) result.completed += 1; }); } return result; }
const percent = (value: Sample) => value.scheduled ? value.completed / value.scheduled * 100 : 0;

export function generateActionableInsights(today: Date, habits: InsightHabit[], categories: { id: string; label: string }[], goals: InsightGoal[]) {
  const todayKey = isoDate(today.getFullYear(), today.getMonth(), today.getDate());
  const activeHabits = habits.filter((habit) => !habit.archived || Boolean(habit.archivedAt && habit.archivedAt > todayKey));
  const insights: (ActionableInsight & { priority: number })[] = [];
  const recentStart = addDays(today, -13); const priorStart = addDays(today, -27);
  const shortDate = (date: Date) => date.toLocaleDateString("es-ES", { day: "numeric", month: "short" });
  const range = (start: Date, days: number) => `${shortDate(start)}–${shortDate(addDays(start, days - 1))}`;
  categories.forEach((category) => { const recent = sample(activeHabits, recentStart, 14, category.id); const prior = sample(activeHabits, priorStart, 14, category.id); const recentPercent = percent(recent); const priorPercent = percent(prior); const drop = priorPercent - recentPercent; if (recent.scheduled >= 6 && prior.scheduled >= 6 && drop >= 15) insights.push({ id: `trend-${category.id}`, kind: "trend", severity: "attention", priority: 90 + drop, title: `${category.label} está perdiendo constancia`, detail: `Ha bajado ${Math.round(drop)} puntos frente a las dos semanas anteriores.`, evidence: `${recent.completed} de ${recent.scheduled} completados (${Math.round(recentPercent)}%), antes ${prior.completed} de ${prior.scheduled} (${Math.round(priorPercent)}%).`, rule: "Aparece si un bloque baja al menos 15 puntos y hay 6 registros válidos en cada periodo.", period: `${range(priorStart, 14)} frente a ${range(recentStart, 14)}`, action: "Revisa qué hábito está generando fricción antes de añadir más carga." }); });

  const weekdays = Array.from({ length: 7 }, () => ({ scheduled: 0, completed: 0 }));
  for (let offset = -55; offset <= 0; offset += 1) { const date = addDays(today, offset); activeHabits.forEach((habit) => { const completed = recordFor(habit, date); if (completed === null) return; weekdays[date.getDay()].scheduled += 1; if (completed) weekdays[date.getDay()].completed += 1; }); }
  const eligible = weekdays.map((entry, weekday) => ({ ...entry, weekday, value: percent(entry) })).filter((entry) => entry.scheduled >= 4);
  const overall = percent(eligible.reduce((total, entry) => ({ scheduled: total.scheduled + entry.scheduled, completed: total.completed + entry.completed }), { scheduled: 0, completed: 0 }));
  const weakest = eligible.sort((a, b) => a.value - b.value)[0];
  if (weakest && overall - weakest.value >= 15) { const names = ["domingos", "lunes", "martes", "miércoles", "jueves", "viernes", "sábados"]; insights.push({ id: "weak-weekday", kind: "weekday", severity: "attention", priority: 70 + overall - weakest.value, title: `Los ${names[weakest.weekday]} son tu punto débil`, detail: `Tu cumplimiento baja ${Math.round(overall - weakest.value)} puntos respecto a tu media reciente.`, evidence: `${weakest.completed} de ${weakest.scheduled} completados los ${names[weakest.weekday]} (${Math.round(weakest.value)}%); media general ${Math.round(overall)}%.`, rule: "Aparece si un día tiene al menos 4 registros y queda 15 puntos o más por debajo de la media.", period: range(addDays(today, -55), 56), action: "Reduce la exigencia de ese día o adelanta el hábito más importante." }); }

  activeHabits.forEach((habit) => { const start = addDays(today, -27); const recent = sample([habit], start, 28); const value = percent(recent); if (recent.scheduled >= 8 && value < 50) insights.push({ id: `habit-${habit.id}`, kind: "habit", entityId: habit.id, severity: "attention", priority: 55 + (50 - value), title: `${habit.name} necesita un rediseño`, detail: `Se ha completado el ${Math.round(value)}% de las veces programadas en 28 días.`, evidence: `${recent.completed} de ${recent.scheduled} ocasiones programadas completadas.`, rule: "Aparece con al menos 8 ocasiones válidas y menos del 50% de cumplimiento.", period: range(start, 28), action: "Reduce la meta, cambia el horario o elimina un obstáculo concreto." }); });

  goals.filter((goal) => goal.status === "active" && !goal.archived).forEach((goal) => { const overdueSteps = (goal.steps ?? []).filter((step) => !step.completed && step.dueDate < todayKey); if (overdueSteps.length) { insights.push({ id: `goal-step-${goal.id}`, kind: "goal", entityId: goal.id, severity: "attention", priority: 110 + overdueSteps.length, title: `${goal.title} tiene pasos vencidos`, detail: `${overdueSteps.length} ${overdueSteps.length === 1 ? "acción o hito necesita" : "acciones o hitos necesitan"} una decisión.`, evidence: overdueSteps.map((step) => `${step.title} (${step.dueDate})`).join(" · "), rule: "Aparece cuando existe al menos un hito o acción sin completar cuya fecha ya pasó.", period: `Estado a ${shortDate(today)}`, action: "Completa, reprograma o elimina cada paso vencido; no lo dejes como deuda invisible." }); return; } const daysLeft = Math.ceil((new Date(`${goal.dueDate}T12:00:00`).getTime() - new Date(`${todayKey}T12:00:00`).getTime()) / 86_400_000); const progress = goal.currentValue / Math.max(1, goal.targetValue) * 100; const riskWindow = goal.period === "weekly" ? 2 : 14; if (daysLeft >= 0 && daysLeft <= riskWindow && progress < 50) insights.push({ id: `goal-risk-${goal.id}`, kind: "goal", entityId: goal.id, severity: "attention", priority: 80 + (riskWindow - daysLeft), title: `${goal.title} está en riesgo`, detail: `Vence en ${daysLeft} ${daysLeft === 1 ? "día" : "días"} y lleva un ${Math.round(progress)}% de avance.`, evidence: `${goal.currentValue} de ${goal.targetValue} completado; fecha límite ${goal.dueDate}.`, rule: `Aparece si quedan ${riskWindow} días o menos y el progreso es inferior al 50%.`, period: `Estado a ${shortDate(today)}`, action: "Define la siguiente acción o ajusta el alcance antes de que venza." }); });
  if (!insights.length) insights.push({ id: "stable", kind: "trend", severity: "positive", priority: 0, title: "El sistema se mantiene estable", detail: "No hay caídas relevantes ni objetivos cercanos en riesgo con los datos disponibles.", evidence: "Ninguna regla de atención supera actualmente su umbral.", rule: "Se muestra cuando no hay señales de caída, baja constancia, vencimientos o riesgo cercano.", period: range(addDays(today, -55), 56), action: "Mantén la carga actual y sigue registrando para detectar cambios reales." });
  return insights.sort((a, b) => b.priority - a.priority).slice(0, 4).map((item): ActionableInsight => ({ id: item.id, kind: item.kind, entityId: item.entityId, title: item.title, detail: item.detail, evidence: item.evidence, rule: item.rule, period: item.period, action: item.action, severity: item.severity }));
}
