import { habitScheduledOnDate, isoDate, type HabitSchedule } from "./tracking";

export type InsightHabit = { id: number; name: string; goal: number; category?: string; archived?: boolean; archivedAt?: string; weekdaysOnly?: boolean; schedule?: HabitSchedule; history?: Record<string, number[]>; skips?: Record<string, number[]> };
export type InsightGoal = { id: number; title: string; dueDate: string; status: "active" | "completed" | "discarded"; archived?: boolean; currentValue: number; targetValue: number; steps?: { title: string; dueDate: string; completed: boolean }[] };
export type ActionableInsight = { id: string; kind: "trend" | "weekday" | "habit" | "goal"; title: string; detail: string; action: string; severity: "attention" | "positive" | "neutral" };
type Sample = { scheduled: number; completed: number };

function addDays(date: Date, amount: number) { const result = new Date(date.getFullYear(), date.getMonth(), date.getDate(), 12); result.setDate(result.getDate() + amount); return result; }
function recordFor(habit: InsightHabit, date: Date) { const key = isoDate(date.getFullYear(), date.getMonth(), date.getDate()); if (!habitScheduledOnDate(habit, key)) return null; const monthKey = key.slice(0, 7); const day = date.getDate(); if ((habit.skips?.[monthKey] ?? []).includes(day)) return null; return (habit.history?.[monthKey] ?? []).includes(day); }
function sample(habits: InsightHabit[], start: Date, days: number, category?: string): Sample { const result = { scheduled: 0, completed: 0 }; for (let offset = 0; offset < days; offset += 1) { const date = addDays(start, offset); habits.filter((habit) => !category || habit.category === category).forEach((habit) => { const completed = recordFor(habit, date); if (completed === null) return; result.scheduled += 1; if (completed) result.completed += 1; }); } return result; }
const percent = (value: Sample) => value.scheduled ? value.completed / value.scheduled * 100 : 0;

export function generateActionableInsights(today: Date, habits: InsightHabit[], categories: { id: string; label: string }[], goals: InsightGoal[]) {
  const todayKey = isoDate(today.getFullYear(), today.getMonth(), today.getDate());
  const activeHabits = habits.filter((habit) => !habit.archived || Boolean(habit.archivedAt && habit.archivedAt > todayKey));
  const insights: (ActionableInsight & { priority: number })[] = [];
  const recentStart = addDays(today, -13); const priorStart = addDays(today, -27);
  categories.forEach((category) => { const recent = sample(activeHabits, recentStart, 14, category.id); const prior = sample(activeHabits, priorStart, 14, category.id); const drop = percent(prior) - percent(recent); if (recent.scheduled >= 6 && prior.scheduled >= 6 && drop >= 15) insights.push({ id: `trend-${category.id}`, kind: "trend", severity: "attention", priority: 90 + drop, title: `${category.label} está perdiendo constancia`, detail: `Ha bajado ${Math.round(drop)} puntos frente a las dos semanas anteriores.`, action: "Revisa qué hábito está generando fricción antes de añadir más carga." }); });

  const weekdays = Array.from({ length: 7 }, () => ({ scheduled: 0, completed: 0 }));
  for (let offset = -55; offset <= 0; offset += 1) { const date = addDays(today, offset); activeHabits.forEach((habit) => { const completed = recordFor(habit, date); if (completed === null) return; weekdays[date.getDay()].scheduled += 1; if (completed) weekdays[date.getDay()].completed += 1; }); }
  const eligible = weekdays.map((entry, weekday) => ({ ...entry, weekday, value: percent(entry) })).filter((entry) => entry.scheduled >= 4);
  const overall = percent(eligible.reduce((total, entry) => ({ scheduled: total.scheduled + entry.scheduled, completed: total.completed + entry.completed }), { scheduled: 0, completed: 0 }));
  const weakest = eligible.sort((a, b) => a.value - b.value)[0];
  if (weakest && overall - weakest.value >= 15) { const names = ["domingos", "lunes", "martes", "miércoles", "jueves", "viernes", "sábados"]; insights.push({ id: "weak-weekday", kind: "weekday", severity: "attention", priority: 70 + overall - weakest.value, title: `Los ${names[weakest.weekday]} son tu punto débil`, detail: `Tu cumplimiento baja ${Math.round(overall - weakest.value)} puntos respecto a tu media reciente.`, action: "Reduce la exigencia de ese día o adelanta el hábito más importante." }); }

  activeHabits.forEach((habit) => { const recent = sample([habit], addDays(today, -27), 28); const value = percent(recent); if (recent.scheduled >= 8 && value < 50) insights.push({ id: `habit-${habit.id}`, kind: "habit", severity: "attention", priority: 55 + (50 - value), title: `${habit.name} necesita un rediseño`, detail: `Se ha completado el ${Math.round(value)}% de las veces programadas en 28 días.`, action: "Reduce la meta, cambia el horario o elimina un obstáculo concreto." }); });

  goals.filter((goal) => goal.status === "active" && !goal.archived).forEach((goal) => { const overdueSteps = (goal.steps ?? []).filter((step) => !step.completed && step.dueDate < todayKey); if (overdueSteps.length) { insights.push({ id: `goal-step-${goal.id}`, kind: "goal", severity: "attention", priority: 110 + overdueSteps.length, title: `${goal.title} tiene pasos vencidos`, detail: `${overdueSteps.length} ${overdueSteps.length === 1 ? "acción o hito necesita" : "acciones o hitos necesitan"} una decisión.`, action: "Completa, reprograma o elimina cada paso vencido; no lo dejes como deuda invisible." }); return; } const daysLeft = Math.ceil((new Date(`${goal.dueDate}T12:00:00`).getTime() - new Date(`${todayKey}T12:00:00`).getTime()) / 86_400_000); const progress = goal.currentValue / Math.max(1, goal.targetValue) * 100; if (daysLeft >= 0 && daysLeft <= 14 && progress < 50) insights.push({ id: `goal-risk-${goal.id}`, kind: "goal", severity: "attention", priority: 80 + (14 - daysLeft), title: `${goal.title} está en riesgo`, detail: `Vence en ${daysLeft} ${daysLeft === 1 ? "día" : "días"} y lleva un ${Math.round(progress)}% de avance.`, action: "Define la siguiente acción o ajusta el alcance antes de que venza." }); });
  if (!insights.length) insights.push({ id: "stable", kind: "trend", severity: "positive", priority: 0, title: "El sistema se mantiene estable", detail: "No hay caídas relevantes ni objetivos cercanos en riesgo con los datos disponibles.", action: "Mantén la carga actual y sigue registrando para detectar cambios reales." });
  return insights.sort((a, b) => b.priority - a.priority).slice(0, 4).map((item): ActionableInsight => ({ id: item.id, kind: item.kind, title: item.title, detail: item.detail, action: item.action, severity: item.severity }));
}
