create table if not exists public.motivational_quotes (
  user_id uuid not null references auth.users(id) on delete cascade,
  id bigint generated by default as identity,
  text text not null check (char_length(trim(text)) between 1 and 220),
  position integer not null default 0,
  created_at timestamptz not null default now(),
  primary key (user_id, id)
);

alter table public.motivational_quotes enable row level security;

create policy "Users manage their motivational quotes" on public.motivational_quotes
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create or replace function public.replace_tracker_state(payload jsonb)
returns void
language plpgsql
security invoker
set search_path = public
as $$
declare
  current_user_id uuid := auth.uid();
begin
  if current_user_id is null then raise exception 'Usuario no autenticado'; end if;

  delete from habit_completions where user_id = current_user_id;
  delete from habits where user_id = current_user_id;
  delete from categories where user_id = current_user_id;
  delete from motivational_quotes where user_id = current_user_id;

  insert into categories (user_id, id, label, icon, color, position)
  select current_user_id, item->>'id', item->>'label', coalesce(item->>'icon', '●'), item->>'color', ordinality::integer - 1
  from jsonb_array_elements(coalesce(payload->'categories', '[]'::jsonb)) with ordinality as category_items(item, ordinality);

  insert into habits (user_id, id, category_id, kind, name, goal, color, position, archived, every_day, celebrated_streak_30)
  select current_user_id, (item->>'id')::bigint, item->>'category', habit_kind, item->>'name', (item->>'goal')::integer,
         item->>'color', ordinality::integer - 1, coalesce((item->>'archived')::boolean, false),
         case when habit_kind = 'daily' then coalesce((item->>'everyDay')::boolean, false) else false end,
         nullif(item->>'celebratedStreak30', '')
  from (
    select item, ordinality, 'daily'::text as habit_kind from jsonb_array_elements(coalesce(payload->'daily', '[]'::jsonb)) with ordinality as daily_items(item, ordinality)
    union all
    select item, ordinality, 'weekly'::text as habit_kind from jsonb_array_elements(coalesce(payload->'weekly', '[]'::jsonb)) with ordinality as weekly_items(item, ordinality)
  ) all_habits;

  insert into habit_completions (user_id, habit_id, period_key, value)
  select current_user_id, (habit->>'id')::bigint, history_entry.key, completion.value::integer
  from (
    select item as habit from jsonb_array_elements(coalesce(payload->'daily', '[]'::jsonb)) item
    union all
    select item as habit from jsonb_array_elements(coalesce(payload->'weekly', '[]'::jsonb)) item
  ) all_habits
  cross join lateral jsonb_each(coalesce(habit->'history', '{}'::jsonb)) history_entry
  cross join lateral jsonb_array_elements_text(history_entry.value) completion
  on conflict do nothing;

  insert into motivational_quotes (user_id, text, position)
  select current_user_id, trim(value), ordinality::integer - 1
  from jsonb_array_elements_text(coalesce(payload->'motivations', '[]'::jsonb)) with ordinality as quote_items(value, ordinality)
  where char_length(trim(value)) between 1 and 220;
end;
$$;

revoke all on function public.replace_tracker_state(jsonb) from public;
grant execute on function public.replace_tracker_state(jsonb) to authenticated;
